languageCode = "es"
languageName = "español"
languageDirection = "ltr"
weight = 1

#title = "Mariano Caruso"
copyright = "© Mariano Caruso"

[params]
  dateFormat = "2 Enero 2006"
  # mainSections = ["section1", "section2"]
  # description = "My excellent website"

[params.author]
  name = "Mariano Caruso"
  image = "img/author.png"
  headline = "la inteligencia me persigue, pero yo soy más rápido"
  bio = "la inteligencia me persigue, pero yo soy más rápido"
  
  links = [
    { linkedin = "https://linkedin.com/in/marianocaruso" },
  # { google-scholar = "https://scholar.google.com/citations?user=tVIaKsYAAAAJ" },
    { google = "https://scholar.google.com/citations?user=tVIaKsYAAAAJ" },
    { arxiv = "https://arxiv.org/a/caruso_m_1.html" },
    { orcid = "https://orcid.org/0000-0002-7455-1193" },
    { github = "https://github.com/marianocaruso" },
  # { x-twitter = "https://twitter.com/mcaruso_" },
  # { researchgate = "https://www.researchgate.net/profile/username" },
  #  { whatsapp = "https://wa.me/phone-number" },
  #  { youtube = "https://youtube.com/username" },
  #  { email = "mailto:hello@your_domain.com" },
  #  { link = "https://link-to-some-website.com/" },
  #  { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #  { apple = "https://www.apple.com" },
  #  { blogger = "https://username.blogspot.com/" },
  #  { codepen = "https://codepen.io/username" },
  #  { dev = "https://dev.to/username" },
  #  { discord = "https://discord.gg/invitecode" },
  #  { dribbble = "https://dribbble.com/username" },
  #  { facebook = "https://facebook.com/username" },
  #  { flickr = "https://www.flickr.com/photos/username/" },
  #  { foursquare = "https://foursquare.com/username" },
  #  { gitlab = "https://gitlab.com/username" },
  #  { google = "https://www.google.com/" },
  #  { hashnode = "https://username.hashnode.dev" },
  #  { instagram = "https://instagram.com/username" },
  #  { keybase = "https://keybase.io/username" },
  #  { kickstarter = "https://www.kickstarter.com/profile/username" },
  #  { lastfm = "https://lastfm.com/user/username" },
  #  { mastodon = "https://mastodon.instance/@username" },
  #  { medium = "https://medium.com/username" },
  #  { mendeley = "https://www.mendeley.com/" },
  #  { microsoft = "https://www.microsoft.com/" },
  #  { patreon = "https://www.patreon.com/username" },
  #  { pinterest = "https://pinterest.com/username" },
  #  { reddit = "https://reddit.com/user/username" },
  #  { slack = "https://workspace.url/team/userid" },
  #  { snapchat = "https://snapchat.com/add/username" },
  #  { soundcloud = "https://soundcloud.com/username" },
  #  { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #  { steam = "https://steamcommunity.com/profiles/userid" },
  #  { telegram = "https://t.me/username" },
  #  { threads = "https://threads.net/@username" },
  #  { tiktok = "https://tiktok.com/@username" },
  #  { tumblr = "https://username.tumblr.com" },
  #  { twitch = "https://twitch.tv/username" },
  #  { xing = "https://xing.com/profile/username" },
  ]